-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'DISTRIBUTOR_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'DISTRIBUTOR_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'LINE_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'LINE_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPENSE_CATEGORY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPENSE_CATEGORY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPENSE_CATEGORY_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPENSE_CATEGORY_DEACTIVATED';
